### PR TITLE
Fix #31: Refactor SdfAbstractDataSpecId to SdfPath as per USD 19.11

### LINKED ISSUE #31: Compiling usd-qt with USD 19.11 and use with maya-usd
### Issue

I'm trying to compile `usd-qt` with the `dev` branch to test it together with [`maya-usd`](https://github.com/Autodesk/maya-usd). 

The latest [`maya-usd/refactoring_sandbox`](https://github.com/Autodesk/maya-usd/tree/refactoring_sandbox) and [`maya-usd/dev`](https://github.com/Autodesk/maya-usd/tree/dev) branches now build on `USD` 19.11. Basically [this USD commit](https://github.com/PixarAnimationStudios/USD/commit/1d08054341653e46cbb7120f65cc97c43133775d) in the `USD/dev`  branch as described [here](https://github.com/Autodesk/maya-usd/blob/e47ca0229dc60158c0a87acbbb404df9117be350/doc/DEVELOPER.md#source-versions). 

However I'm unable to compile `usd-qt` with that USD version.
I ran `cmake` using a somewhat equivalent of:
```bat
:: USD_ROOT is the compiled USD root.
set USD_ROOT=D:\dev\usd\build

:: Dependencies
set TBB_INCLUDE_DIR=%USD_ROOT%/src/tbb2017_20170226oss
set Boost_INCLUDE_DIR=%USD_ROOT%/include/boost-1_65_1

:: Output directory
set BUILD_DIR=D:\dev\usd\usd-qt-build

:: Cmake build
cd /D D:\dev\usd\usd-qt
cmake -G "Visual Studio 15 2017 Win64" -DBoost_INCLUDE_DIR="%Boost_INCLUDE_DIR%" -DTBB_ROOT_DIR="%TBB_INCLUDE_DIR%" -DBOOST_LIBRARYDIR=%USD_ROOT%/lib -B %BUILD_DIR%
```

And then build the `usdqt.sln` solution using Visual Studio.

Which gave me this output:
[usdqt_build_release_log.txt](https://github.com/LumaPictures/usd-qt/files/3794759/usdqt_build_release_log.txt)

Note the build failure and the errors that occurred, like:
```
5>d:\dev\usd\usd-qt\pxr\usdqt\undoStateDelegate.h(90): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
5>d:\dev\usd\usd-qt\pxr\usdqt\undoStateDelegate.h(90): error C2143: syntax error: missing ',' before '&'
5>d:\dev\usd\usd-qt\pxr\usdqt\undoStateDelegate.h(92): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
5>d:\dev\usd\usd-qt\pxr\usdqt\undoStateDelegate.h(92): error C2143: syntax error: missing ',' before '&'
```

And:
```
5>d:\dev\usd\usd-qt\pxr\usdqt\undoStateDelegate.h(90): error C3668: 'pxrInternal_v0_19__pxrReserved__::UsdQt_UndoStateDelegate::_OnSetField': method with override specifier 'override' did not override any base class methods
5>d:\dev\usd\usd-qt\pxr\usdqt\undoStateDelegate.h(98): error C3668: 'pxrInternal_v0_19__pxrReserved__::UsdQt_UndoStateDelegate::_OnSetFieldDictValueByKey': method with override specifier 'override' did not override any base class methods
5>d:\dev\usd\usd-qt\pxr\usdqt\undoStateDelegate.h(110): error C3668: 'pxrInternal_v0_19__pxrReserved__::UsdQt_UndoStateDelegate::_OnSetTimeSample': method with override specifier 'override' did not override any base class methods
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): error C2259: 'pxrInternal_v0_19__pxrReserved__::UsdQt_UndoStateDelegate': cannot instantiate abstract class
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): note: due to following members:
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): note: 'void pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetField(const pxrInternal_v0_19__pxrReserved__::SdfPath &,const pxrInternal_v0_19__pxrReserved__::TfToken &,const pxrInternal_v0_19__pxrReserved__::SdfAbstractDataConstValue &)': is abstract
5>D:\dev\usd\build\include\pxr/usd/sdf/layerStateDelegate.h(187): note: see declaration of 'pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetField'
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): note: 'void pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetField(const pxrInternal_v0_19__pxrReserved__::SdfPath &,const pxrInternal_v0_19__pxrReserved__::TfToken &,const pxrInternal_v0_19__pxrReserved__::VtValue &)': is abstract
5>D:\dev\usd\build\include\pxr/usd/sdf/layerStateDelegate.h(183): note: see declaration of 'pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetField'
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): note: 'void pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetFieldDictValueByKey(const pxrInternal_v0_19__pxrReserved__::SdfPath &,const pxrInternal_v0_19__pxrReserved__::TfToken &,const pxrInternal_v0_19__pxrReserved__::TfToken &,const pxrInternal_v0_19__pxrReserved__::SdfAbstractDataConstValue &)': is abstract
5>D:\dev\usd\build\include\pxr/usd/sdf/layerStateDelegate.h(198): note: see declaration of 'pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetFieldDictValueByKey'
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): note: 'void pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetFieldDictValueByKey(const pxrInternal_v0_19__pxrReserved__::SdfPath &,const pxrInternal_v0_19__pxrReserved__::TfToken &,const pxrInternal_v0_19__pxrReserved__::TfToken &,const pxrInternal_v0_19__pxrReserved__::VtValue &)': is abstract
5>D:\dev\usd\build\include\pxr/usd/sdf/layerStateDelegate.h(193): note: see declaration of 'pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetFieldDictValueByKey'
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): note: 'void pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetTimeSample(const pxrInternal_v0_19__pxrReserved__::SdfPath &,double,const pxrInternal_v0_19__pxrReserved__::SdfAbstractDataConstValue &)': is abstract
5>D:\dev\usd\build\include\pxr/usd/sdf/layerStateDelegate.h(209): note: see declaration of 'pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetTimeSample'
5>D:\dev\usd\usd-qt\pxr\usdQt\undoStateDelegate.cpp(40): note: 'void pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetTimeSample(const pxrInternal_v0_19__pxrReserved__::SdfPath &,double,const pxrInternal_v0_19__pxrReserved__::VtValue &)': is abstract
5>D:\dev\usd\build\include\pxr/usd/sdf/layerStateDelegate.h(205): note: see declaration of 'pxrInternal_v0_19__pxrReserved__::SdfLayerStateDelegateBase::_OnSetTimeSample'
```

I get the same output when building through `cmake --build %BUILD_DIR% --config Release`

---

It's very likely I did something wrong regarding the cmake or build step. Any tips would be very welcome!

For completeness sake, I built `USD` using:
```bat
%PYTHON% build_scripts/build_usd.py --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya %USD_BUILD_DIR%
```

### PR DESCRIPTION
**Pull request by BigRoy**
This refactors `SdfAbstractDataSpecId` and updates the `SdfAbstractData` interface to use `SdfPath` for compiling against USD 19.11. The [USD 19.11 changelog states about this](https://github.com/PixarAnimationStudios/USD/blob/dev/CHANGELOG.md#1911---2019-10-18):

> Removed SdfAbstractDataSpecId and updated the SdfAbstractData interface to use SdfPath in its place. Existing SdfAbstractData subclasses must be updated to match. See this usd-interest post for more details: https://groups.google.com/forum/#!topic/usd-interest/IVmd1t1GKBA

I've tried to refactor the code similar to the example links the Changelog links to. So hopefully everything works as expected.

I was able to compile with this change, but have not _yet_ tested whether the tools still continue to work. I'm opening this PR already to discuss code changes and have others test it too.

Having others test it is especially useful as I've never used `usd-qt` before and the extent of my tests or success of using it might be totally related to other things.

### CODE REVIEW

**Comment by BigRoy** [comment]
I can confirm this works fine when compiled with USD 19.11 (I used latest `USD/dev`). I was able to open the `outliner` and `hierarchyEditor` editors as an example just fine. 👍 I was running them inside of Maya 2019.2 on Windows 10 but that should be irrelevant information.

Note: that by merging this it becomes incompatible with versions before USD 19.11 because of the API change.

**Comment by nrusch** [comment]
Thanks for this. I don't think we're quite ready to drop support for all older versions just yet, so I think we'll need to implement some conditional preprocessor switching in here. I'll play with some ideas later today or on Monday, but if you want to take a crack at it as well, feel free.

**Comment by BigRoy** [comment]
@nrusch I'm currently solely testing with the latest ` 0.19.11`  so unfortunately I don't think I'll find the time to implement and test the preprocessor conditional switching for the older USD API prior to `0.19.11`. However, feel free to push into this PR if you've tested against older versions and I'll be happy to recompile and see if everything is good with the latest.

**Comment by nrusch** [comment]
OK, I had a change of heart about the need to support older USD versions after thinking it over a bit. We talked over it a bit internally, and agree that there's not much of a reason to worry about compatibility that much with this project (at least not yet), so I'll go ahead and merge this. Thanks for the contribution!

**Comment by BigRoy** [comment]
> We talked over it a bit internally, and agree that there's not much of a reason to worry about compatibility that much with this project (at least not yet), so I'll go ahead and merge this. Thanks for the contribution!

Perfect. 🚀 

- Should we branch of the current state into a `0.19.10-` branch or alike for anyone looking for it? Or maybe tag a commit so it's clear where compatibility changed?
- With it so clearly being incompatible with the older API, should the project somewhere have a statement of what USD version is expected to compile against?

**Comment by nrusch** [comment]
> Should we branch of the current state into a 0.19.10- branch or alike for anyone looking for it? Or maybe tag a commit so it's clear where compatibility changed?

That sounds like it could potentially fit for the master branch, although I'm still a little hesitant. 

We use a modified version of the USD dev branch internally, so our notion of USD "versions" is a bit different from the releases on the USD master branch, and I don't think we want to tie UsdQt's master branch to the USD cadence when it comes to tagging releases. Given that A) this project is pretty low-entropy at this stage, and B) USD is still technically not 1.0 software, I'm inclined to take a "wait-and-see" approach: If multi-version compatibility starts to become a thorn in peoples' side, then I would be happy to circle back and try to formalize things a bit more.

That said, I do think keeping the README updated with an indication of the compatibility of the various branches is a great idea. I'll get that updated shortly.
